---
language: python
python: 2.7

env:
  matrix:
  - ANSIBLE_VERSION=1.9.4   ANSIBLE_EXTRA_VARS='exhibitor_config_type=s3'
  - ANSIBLE_VERSION=2.0.0.2 ANSIBLE_EXTRA_VARS='exhibitor_config_type=s3'
  - ANSIBLE_VERSION=1.9.4   ANSIBLE_EXTRA_VARS='exhibitor_config_type=none'
  - ANSIBLE_VERSION=2.0.0.2 ANSIBLE_EXTRA_VARS='exhibitor_config_type=none'

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible==$ANSIBLE_VERSION
  - cd tests
  - ansible-galaxy install -r requirements.yml

script:
  - "ansible-playbook -i 'localhost,' playbook.yml --extra-vars=$ANSIBLE_EXTRA_VARS --syntax-check"
  - "ansible-playbook -i 'localhost,' playbook.yml --extra-vars=$ANSIBLE_EXTRA_VARS --connection=local --sudo"
  - >
    ansible-playbook -i 'localhost,' playbook.yml --extra-vars=$ANSIBLE_EXTRA_VARS --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
